Models/Assignment.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Homework_Log.Models {
    public class Assignment {
        [Key]
        public int ID { get; set; }
        
        [Required]
        public string? AssignmentName { get; set; }

        [Required]
        public DateTime DueDate { get; set; }

        public bool IsCompleted { get; set; }

        public int MaxPoints { get; set; }

        public int PointsEarned { get; set; }

        [Required]
        public int CourseID { get; set; }
        
        [ForeignKey("CourseID")]
        public virtual Course Course { get; set; }
        // do i just make the course property a string and only use the courseID to reference the course??? 

        public string CourseName { get; set; } = string.Empty;
    }
}

Models/Course.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Homework_Log.Models {
	public class Course {
		[Key]
		public int ID{ get; set; }

		[Required]
		[DisplayName("Course Name")]
		public string? CourseName{ get; set; }

		[DisplayName("Display Order")]
		public int? DisplayOrder { get; set; }
		public DateTime CreatedDateTime { get; set; } = DateTime.Now;
		
		public virtual ICollection<Assignment>? Assignments { get; set; }

		// one to many relations. Order = assignment | Customer = course   course can have multiple assigments but an assignemnt can only have one course
		//

	}
}

Models/ErrorViewModel.cs
namespace Homework_Log.Models {
    public class ErrorViewModel {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AssignmentController.cs
using Homework_Log.Data;
using Homework_Log.Models;
using Microsoft.AspNetCore.Mvc;

namespace Homework_Log.Controllers
{
	public class AssignmentController : Controller
	{

		// gives access to read from DI container 
		private readonly ApplicationDbContext _db;

		// init DI container
		public AssignmentController(ApplicationDbContext db)
		{
			_db = db;
		}

		public IActionResult Index()
		{
			IEnumerable<Assignment> objAssignmentList = _db.Assignments.OrderBy(a => a.DueDate);
			return View(objAssignmentList);
		}


		//GET
		public IActionResult Create(int CourseId)
		{
			Course courseDb = _db.Courses.Find(CourseId);
			ViewBag.Course = courseDb;
			ViewBag.CourseName = courseDb.CourseName;
			ViewBag.CourseId = courseDb.ID;
			return View();
		}

		//POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create([Bind("AssignmentName, DueDate, CourseID, MaxPoints")] Assignment assignment)
		{
			Course course = _db.Courses.Find(assignment.CourseID);
			assignment.Course = course;
			assignment.CourseName = course.CourseName;
			int courseID = assignment.CourseID;
			/*if (ModelState.IsValid)
			{
				*//*course.Assignments.Add(assignment);*//*
				_db.Assignments.Add(assignment);
				_db.SaveChanges();
				return RedirectToAction("Index");
			}*/
			_db.Assignments.Add(assignment);
			_db.SaveChanges();
			return RedirectToAction("Details", "Course", new { id = courseID });
		}


		//GET
		public ActionResult Delete(int? id, int courseID)
		{
			ViewBag.CourseName = _db.Courses.Find(courseID).CourseName;
			ViewBag.CourseID = courseID;
			if (id == null || id == 0)
			{
				return NotFound();
			}
			var AssignmentFromDb = _db.Assignments.Find(id);

			if (AssignmentFromDb == null)
			{
				return NotFound();
			}

			return View(AssignmentFromDb);
		}

		//POST 
		[HttpPost]
		public IActionResult DeletePOST(int? id, int courseID)
		{
			var obj = _db.Assignments.Find(id);

			if (obj == null)
			{
				TempData["fail"] = "Error deleting course";
				NotFound();
			}

			_db.Assignments.Remove(obj);
			_db.SaveChanges();
			TempData["success"] = "Assignment successfully deleted";
			return RedirectToAction("Details", "Course", new { id = courseID });
		}


		//GET
		public IActionResult Edit(int? id, int courseID)
		{
			ViewBag.CourseID = courseID;
			ViewBag.CourseName = _db.Courses.Find(courseID).CourseName;
			if (id == null || id == 0)
			{
				return NotFound();
			}
			var assignmentFromDb = _db.Assignments.Find(id);

			if (assignmentFromDb == null)
			{
				return NotFound();
			}

			return View(assignmentFromDb);
		}

		//POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Assignment obj, int courseID)
		{
			// model state is going to compare the object you are trying to access to the model class and see if all required fields are valid 
			/*if (ModelState.IsValid)
			{*/
				_db.Assignments.Update(obj);
				_db.SaveChanges();
				TempData["success"] = "Assignment successfully updated";
			return RedirectToAction("Details", "Course", new { id = courseID });
			
			/*TempData["fail"] = "Error changing course";
			return View(obj);*/
		}

	}
}

Controllers/CourseController.cs
using Homework_Log.Data;
using Homework_Log.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Homework_Log.Controllers {
	public class CourseController : Controller {

		// gives access to read from DI container 
		private readonly ApplicationDbContext _db;

		// init DI container
		public CourseController(ApplicationDbContext db) {
			_db = db;
		}

		public IActionResult Index() {
			IEnumerable<Course> objCourseList = _db.Courses.Include(n => n.Assignments.OrderBy(o=>o.DueDate));
			//if(objCourseList contains any assingments with due date sooner than 1 day ){
			foreach (var course in objCourseList) 
			{
				foreach(var assignment in course.Assignments)
                {
					
					if((assignment.DueDate - DateTime.Now).TotalHours <= 36)
                    {
						ViewBag.AlertMsg = "Assignment Due Very Soon";
						break;
					}
					else if((assignment.DueDate - DateTime.Now).TotalHours <= 48){
						ViewBag.AlertMsg = "Assignment Due Soon";
						continue;
					}
					/*else if((ViewBag.AlertMsg != "Assignment Due Soon" || ViewBag.AlertMsg != "Assignment Due Very Soon") && (assignment.DueDate - DateTime.Now).TotalDays >= 3)
                    {
						ViewBag.AlertMsg = "";
					}*/
                }
			}
			return View(objCourseList);
			// return View( _db.Courses.ToList()); -- other option
		}

		//GET
		public IActionResult Create() {
			return View();
		}

		//POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(Course course) {
			if (ModelState.IsValid)
			{
				course.DisplayOrder = 1;
				_db.Add(course);
				_db.SaveChanges();
				return RedirectToAction(nameof(Index));
				TempData["success"] = "Course successfully Added";
			}
			TempData["fail"] = "Error Adding Course";
			return View(course);
		}

		//GET
		public IActionResult Edit(int? id) {
			if (id == null || id == 0) {
				return NotFound();
			}
			var courseFromDb = _db.Courses.Find(id);

			if (courseFromDb == null) {
				return NotFound();
			}

			return View(courseFromDb);
		}

		//POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(Course obj) {
			// model state is going to compare the object you are trying to access to the model class and see if all required fields are valid 
			if (ModelState.IsValid) {
				obj.DisplayOrder = 1;
				_db.Courses.Update(obj);
				_db.SaveChanges();
				TempData["success"] = "Course successfully changed";
				return RedirectToAction("Index");
			}
			TempData["fail"] = "Error changing course";
			return View(obj);
		}


		//GET
		public ActionResult Delete(int? id) {
			if (id == null || id == 0) {
				return NotFound();
            }
			var CourseFromDb = _db.Courses.Find(id);

			if (CourseFromDb == null) {
				return NotFound();
			}

			return View(CourseFromDb);
		}

		//POST 
		[HttpPost]
		public IActionResult DeletePOST(int? id) {
			// if i delete a course, need to make sure all the assignments linked to course will be removed
			var obj = _db.Courses.Find(id);
			
			if(obj == null) {
				TempData["fail"] = "Error deleting course";
				NotFound();
            }

			_db.Courses.Remove(obj);
			_db.SaveChanges();
			TempData["success"] = "Course successfully deleted";
			return RedirectToAction("Index");
			
		}

		// GET
		public IActionResult Details(int id)
		{
			Course CourseFromDb = _db.Courses.Find(id);
			_db.Entry(CourseFromDb).Collection(p => p.Assignments).Query().OrderBy(p => p.DueDate).Load();
			return View(CourseFromDb);
		}

	}
}

Views/Assignment/Create.cshtml
@model Assignment

@{
    ViewData["Title"] = "Create";
}
@*right now the issue is that the modelstate isnt finding the course assicoated with the assignment*@
  
@*I am trying to go from an action with specfic id to another controller action with a linked id to orginal model(creating new item with reference to orginally object)*@
<div class="row mt-4 text">
    <div class="col-md-8 offset-3">
        <h1>Add Assignment</h1>

        <div class="row">
            <div class="col-8">
                <form asp-action="Create" asp-controller="Assignment">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <input type="hidden" class="form-control" asp-for="CourseID"/>
                        <input type="hidden" asp-for="Course" />

                        <div class="form-group">
                            <label class="float-start">Course</label>
                            <input class="form-control" value="@ViewBag.CourseName" disabled/>
                        </div>
                        <div class="form-group">
                            <label asp-for="AssignmentName" class="float-start">Assignment</label>
                            <input asp-for="AssignmentName" class="form-control"/>
                            <span asp-validation-for="AssignmentName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DueDate" class="float-start">Due Date</label>
                            <input asp-for="DueDate" class="form-control"/>
                            <span asp-validation-for="DueDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="MaxPoints" class="float-start">Total Points</label>
                            <input asp-for="MaxPoints" class="form-control"/>
                            <span asp-validation-for="MaxPoints" class="text-danger"></span>
                        </div>
                        
                        <div class="form-group mt-2">
                            <input type="submit" value="Create" class="btn btn-primary float-end"/>
                            <a class="btn btn-secondary float-start" onclick="history.go(-1)">Show All</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Assignment/Delete.cshtml
@model Assignment

@{
    ViewData["Title"] = "Delete";
}
@*right now the issue is that the modelstate isnt finding the course assicoated with the assignment*@

@*I am trying to go from an action with specfic id to another controller action with a linked id to orginal model(creating new item with reference to orginally object)*@
<div class="row mt-4 text">
    <div class="col-md-8 offset-3">
        <h1>Delete Assignment</h1>
        <div class="row">
            <div class="col-8">
                <form asp-action="DeletePOST" asp-controller="Assignment">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <input type="hidden" asp-for="ID"/>
                        <div class="form-group">
                            <label class="float-start">Course</label>
                            <input class="form-control" value="@ViewBag.CourseName" disabled/>
                        </div>
                        <div class="form-group">
                            <label asp-for="AssignmentName" class="float-start">Assignment</label>
                            <input asp-for="AssignmentName" class="form-control" disabled/>
                            <span asp-validation-for="AssignmentName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DueDate" class="float-start">Due Date</label>
                            <input asp-for="DueDate" class="form-control" disabled/>
                            <span asp-validation-for="DueDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="MaxPoints" class="float-start">Total Points</label>
                            <input asp-for="MaxPoints" class="form-control" disabled/>
                            <span asp-validation-for="MaxPoints" class="text-danger"></span>
                        </div>
                        <input type="hidden" asp-for="Course" />
                        
                        <div class="form-group mt-2">
                            <input type="submit" value="Delete" class="btn btn-danger float-end"/>
                            <a class="btn btn-secondary float-start" asp-controller="Assignment" asp-action="Index">Show All</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@*
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Add Assignment</h2>
            <hr />
        </div>

        <button type="submit" value="Create" class="btn btn-primary" style="width: 150px;">Create</button>
        <a asp-controller="Course" asp-action="Index" class="btn btn-secondary" style="width:150px;">Back to Course</a>
    </div>
</form>
*@
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Assignment/Edit.cshtml
@model Assignment

@{
    ViewData["Title"] = "Edit";
}
@*right now the issue is that the modelstate isnt finding the course assicoated with the assignment*@

@*I am trying to go from an action with specfic id to another controller action with a linked id to orginal model(creating new item with reference to orginally object)*@
<div class="row mt-4 text">
    <div class="col-md-8 offset-3">
        <h1>Edit Assignment</h1>
        <div class="row">
            <div class="col-8">
                <form asp-action="Edit" asp-controller="Assignment">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <input type="hidden" class="form-control" asp-for="CourseID"/>
                        <input type="hidden" asp-for="Course" />
                        <div class="form-group">
                            <label class="float-start">Course</label>
                            <input class="form-control" value="@ViewBag.CourseName" disabled/>
                        </div>
                        <div class="form-group">
                            <label asp-for="AssignmentName" class="float-start">Assignment</label>
                            <input asp-for="AssignmentName" class="form-control"/>
                            <span asp-validation-for="AssignmentName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DueDate" class="float-start">Due Date</label>
                            <input asp-for="DueDate" class="form-control"/>
                            <span asp-validation-for="DueDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="MaxPoints" class="float-start">Total Points</label>
                            <input asp-for="MaxPoints" class="form-control"/>
                            <span asp-validation-for="MaxPoints" class="text-danger"></span>
                        </div>
                        
                        <div class="form-group mt-2">
                            <input type="submit" value="Update" class="btn btn-primary float-end"/>
                            <a class="btn btn-secondary float-start" onclick="history.go(-1)">Show All</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Assignment/Index.cshtml
@model IEnumerable<Assignment>

@{
    ViewData["Title"] = "Course details";
}

<div class="row">
    <div class="col-md-6 offset-3">
        <h1>Assignments</h1>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Assignment</th>
                    <th scope="col">Due Date</th>
                    <th scope="col">Course</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var assignment in Model)
                {
                    <tr>
                        <td>@assignment.AssignmentName</td>
                        <td>@assignment.DueDate</td>
                        <td>@assignment.CourseName<td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Course/Create.cshtml
@model Course

@{
    ViewData["Title"] = "Create";
}

<div class="row mt-4 text">
    <div class="col-md-8 offset-3">
        <h1>Create Course</h1>
        <div class="row">
            <div class="col-8">
                <form method="post" asp-action="Create" asp-controller="Course">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <div class="form-group">
                            <label class="float-start">Course</label>
                            <input class="form-control" asp-for="CourseName"/>
                            <span asp-validation-for="CourseName" class="text-danger"></span>
                        </div>
                        <div class="form-group mt-2">
                            <input type="submit" value="Create" class="btn btn-primary float-end"/>
                            <a class="btn btn-secondary float-start" asp-controller="Course" asp-action="Index">Show All</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Course/Delete.cshtml
@model Course

@{
    ViewData["Title"] = "Create";
}

@*
ToDO
add warning about deleteing all assignments and list them under *@

<div class="row mt-4 text">
    <div class="col-md-8 offset-3">
        <h1>Delete Course</h1>
        <div class="row">
            <div class="col-8">
                <form method="post" asp-action="DeletePOST" asp-controller="Course">
                    <input asp-for="ID" hidden />
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <div class="form-group">
                            <label class="float-start">Course</label>
                            <input class="form-control" asp-for="CourseName" disabled/>
                        </div>
                        <div class="form-group mt-2">
                            <input type="submit" value="Delete" class="btn btn-danger float-end"/>
                            <a class="btn btn-secondary float-start" asp-controller="Course" asp-action="Index">Show All</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Course/Details.cshtml
@model Course

@{
    ViewData["Title"] = "Course details";
}

<div class="flex-md-row justify-content-center">
            <a asp-controller="Assignment" asp-action="Create" asp-route-CourseId="@Model.ID" style="float:right;margin-top:20px; margin-right:10px;" class="btn btn-primary bg-success ">
                    Add Assignment &nbsp;
                    <i class="bi bi-plus-circle"></i>
            </a>
</div>


<div class="">
    <div class="col-md-7 offset-3">
        <h1>@Model.CourseName</h1>

        @if(Model.Assignments == null || Model.Assignments.Count() == 0)
        {
            <p>No Current Assignments</p>
        }
        else{
            <table class="table">
            <thead>
                <tr>
                    <th scope="col">Assignment</th>
                    <th scope="col">Due Date</th>
                    <th scope="col">Points Earned</th>
                    <th scope="col">Total Points</th>
                    <th scope="col">Completed</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var assignment in @Model.Assignments)
                {
                    <tr>
                        <td>@assignment.AssignmentName</td>
                        <td>@assignment.DueDate</td>
                        <td>@assignment.PointsEarned</td>
                        <td>@assignment.MaxPoints</td>
                        <td>@assignment.IsCompleted</td>
                        <td>
                            <a class="btn-danger btn" asp-action="Delete" asp-controller="Assignment" asp-route-id="@assignment.ID" asp-route-courseID="@Model.ID">Delete</a>
                            <a class="btn btn-primary" asp-action="Edit" asp-controller="Assignment" asp-route-id="@assignment.ID" asp-route-courseID="@Model.ID">Edit</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        }
        
    </div>

</div>

Views/Course/Edit.cshtml
@model Course

@{
    ViewData["Title"] = "Create";
}

<div class="row mt-4 text">
    <div class="col-md-8 offset-3">
        <h1>Edit Course</h1>
        <div class="row">
            <div class="col-8">
                <form method="post" asp-action="Edit" asp-controller="Course">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-center">
                        <div class="form-group">
                            <label class="float-start">Course</label>
                            <input class="form-control" asp-for="CourseName"/>
                            <span asp-validation-for="CourseName" class="text-danger"></span>
                        </div>
                        <div class="form-group mt-2">
                            <input type="submit" value="Update" class="btn btn-primary float-end"/>
                            <a class="btn btn-secondary float-start" asp-controller="Course" asp-action="Index">Show All</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Course/Index.cshtml
@model IEnumerable<Course>

@{
    ViewData["Title"] = "Course list";
}
<div class="flex-md-row justify-content-center">
            <a asp-controller="Course" asp-action="Create" style="float:right;margin-top:20px; margin-right:10px;" class="btn btn-primary bg-success ">
                    &nbsp; Add Course &nbsp; <i class="bi bi-plus-circle"></i>
            </a>
</div>


<div class="row">
    @foreach (var item in Model)
    {
        @*style="cursor:pointer;" onclick="location.href= 'Course/Details/@item.ID'"*@
        <div class="col-md-4 col-xs-6 col-lg-3 border-primary mb-3 mt-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.CourseName
                                    <a style="margin-left:8px;" class="text-danger float-end" asp-action="Delete" asp-route-id="@item.ID"><i class="bi bi-trash3"></i></a>
                                    <a class="text-white float-end" asp-action="Edit" asp-route-id="@item.ID"><i class="bi bi-pencil-square"></i></a> 
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div style="height:200px; width:200%; overflow:hidden" class="card-body">
                            @for(var i = 0; i < @item.Assignments.Count(); i++)
                            {
                                @if (i >= 4)
                                {
                                    <p> Click to see full List</p>
                                }
                                <ul>
                                    <li>@item.Assignments.ElementAt(i).AssignmentName.Trim('"') 
                                        <span class="float-end">@item.Assignments.ElementAt(i).DueDate</span>
                                    </li>
                                </ul>  
                            }
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.ID"> View Course</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<div class="row">
    <div style="position:fixed; bottom: 10%; right:0px; width:30%">
        @if (@ViewBag.AlertMsg == "Assignment Due Very Soon")
        {
            <h2 class="alert alert-danger">@ViewBag.AlertMsg</h2>
        }
        @if (@ViewBag.AlertMsg == "Assignment Due Soon")
        {
            <h1 class="alert alert-warning">@ViewBag.AlertMsg</h1>
        }
    </div>
    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Homework_Log</title>
	<link rel="stylesheet" href="~/css/bootswatchTheme.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Homework_Log.styles.css" asp-append-version="true"/>
	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Course" asp-action="Index">Homework Log</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarColor01">
					<ul class="navbar-nav me-auto">
						<li class="nav-item">
							<a class="nav-link" asp-controller="Course" asp-action="Index">Course</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Assignment" asp-action="Index">Assignments</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Course" asp-action="Index">Calendar View</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">About</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container-fluid">
		<main role="main" class="pb-3">
			<partial name="_Notification" />
			@RenderBody()
		</main>
	</div>

	<footer style="bottom:5%; position:absolute; width:100%;" class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - Homework Log - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData["success"]');
	</script>
}

@if(TempData["fail"] != null){
		<script src="~/libjquery/dist/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.warning('@TempData["fail"]');
	</script>
}